// Expire abandoned PayMongo checkout sessions.
//
// PayMongo Checkout Sessions never expire on their own, and this account has no
// checkout_session.expired event, so nothing would ever tell JMAC that a
// payment was abandoned. Without this sweep an abandoned session stays payable
// indefinitely: a customer could reopen yesterday's URL and pay a basket the
// shop wrote off, and the sale would then be built from a stale cart.
//
// Called on a schedule by pg_cron. It is deliberately not a user-facing
// endpoint and it can never create a sale on its own -- when it discovers a
// payment that actually succeeded it defers to the same finalize_pos_payment
// the webhook uses.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { settleSession } from '../_shared/paymongo.ts'

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })
}

/** Constant-time compare, so the token cannot be discovered a byte at a time. */
function tokensMatch(a: string, b: string): boolean {
  const ea = new TextEncoder().encode(a)
  const eb = new TextEncoder().encode(b)
  if (ea.length !== eb.length) return false
  let diff = 0
  for (let i = 0; i < ea.length; i++) diff |= ea[i] ^ eb[i]
  return diff === 0
}

Deno.serve(async (req: Request) => {
  if (req.method !== 'POST') return json({ error: 'Method not allowed.' }, 405)

  try {
    const secret = Deno.env.get('PAYMONGO_SECRET_KEY')

    const admin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    )

    // The expected token lives in Vault, generated by the database itself. It
    // is never typed by a person and never leaves the server -- pg_cron reads
    // it to send, this reads it to check.
    const { data: sweepToken, error: tokenError } = await admin.rpc('pos_expiry_token')
    if (tokenError || !sweepToken) {
      console.error('sweep token is not configured; refusing to sweep.')
      return json({ error: 'Sweep not configured.' }, 503)
    }

    const presented = req.headers.get('x-jmac-expiry-token') ?? ''
    if (!tokensMatch(presented, sweepToken as string)) {
      console.error('sweep token mismatch; rejecting.')
      return json({ error: 'Not authorised.' }, 401)
    }

    if (!secret) return json({ error: 'Payment provider is not configured.' }, 503)
    if (!secret.startsWith('sk_test_')) {
      console.error('PAYMONGO_SECRET_KEY is not a test key; refusing.')
      return json({ error: 'Payment provider is not in test mode.' }, 503)
    }

    const { data: due, error } = await admin.rpc('get_expirable_pos_payments', { _limit: 50 })
    if (error) {
      console.error('could not list expirable payments:', error.message)
      return json({ error: 'Sweep failed.' }, 500)
    }

    const summary = { checked: 0, expired: 0, finalized: 0, left: 0, lost_race: 0 }

    for (const attempt of (due ?? []) as {
      id: string
      provider_checkout_session_id: string | null
      reference_number: string
    }[]) {
      summary.checked += 1

      // No session was ever created at the provider, so there is nothing that
      // could be paid. Safe to close locally.
      if (!attempt.provider_checkout_session_id) {
        const { data: won } = await admin.rpc('mark_pos_payment_state', {
          _attempt_id: attempt.id,
          _status: 'expired',
          _reason: 'expired before a provider session existed',
        })
        if (won) summary.expired += 1
        else summary.lost_race += 1
        continue
      }

      // Kill it at PayMongo FIRST. Recording the outcome locally while the
      // session is still live is the one order that leaves a written-off basket
      // payable.
      const outcome = await settleSession(secret, attempt.provider_checkout_session_id)

      if (outcome.action === 'finalize') {
        // The customer did pay, we just never heard about it. Hand it to the
        // same routine the webhook uses; it is idempotent and re-checks the
        // amount, so a webhook arriving at the same moment is harmless.
        const { data: result, error: finalizeError } = await admin.rpc('finalize_pos_payment', {
          _attempt_id: attempt.id,
          _provider_payment_id: outcome.paymentId,
          _paid_centavos: outcome.paidCentavos,
        })
        if (finalizeError) {
          console.error(`finalize failed for ${attempt.id}: ${finalizeError.message}`)
          summary.left += 1
        } else {
          console.log(`sweep finalized ${attempt.id} -> ${(result as { status?: string })?.status}`)
          summary.finalized += 1
        }
        continue
      }

      if (outcome.action === 'expire') {
        // The session is dead at the provider. The compare-and-set decides
        // whether this sweep or a concurrent webhook records the outcome; if
        // the webhook won, the payment is paid and must stay that way.
        const { data: won } = await admin.rpc('mark_pos_payment_state', {
          _attempt_id: attempt.id,
          _status: 'expired',
          _reason: 'checkout session expired at the provider',
        })
        if (won) {
          summary.expired += 1
          console.log(`sweep expired ${attempt.id}`)
        } else {
          summary.lost_race += 1
          console.log(`sweep did not change ${attempt.id}; another writer got there first`)
        }
        continue
      }

      // Could not establish the state. Leave it pending and try next sweep --
      // a pending attempt costs a cashier one Cancel press, expiring a paid
      // session costs a customer their money.
      console.log(`sweep left ${attempt.id} alone: ${outcome.reason}`)
      summary.left += 1
    }

    return json({ ok: true, ...summary })
  } catch (err) {
    console.error('expire-pos-payments unhandled:', err instanceof Error ? err.message : err)
    return json({ error: 'Sweep failed.' }, 500)
  }
})
